name: Testing Smart Contracts

on:
  push:
    branches:
      - "main"

jobs:
  test-smart-contracts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install dependencies
        run:  cd ./smart-contract && npm install
      - name: Compile Contracts
        run:  cd ./smart-contract && npm run compile
      - name: Run Tests
        run:  cd ./smart-contract && npm run test

  testing-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install dependencies
        run:  cd ./server && npm install
      - name: Transpile Typescript
        run:  cd ./server && npm run build
      - name: Run Tests
        run:  cd ./server && npm run test
      